# -*- coding: utf-8 -*-
"""TREINO ENVIAR FOR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1Swq8RMeZIFWPuM_UFQiDqlgzfzVzxf

1- Faça um programa que leia 5 números e informe o maior número.
"""

maior_numero: float("-inf")

for programa in range(1,6):
  numero = float(input(f"Digite o {programa} º numero: "))
  if numero > maior_numero:
    maior_numero = numero
    print(f"O maior numero digitado e: {maior_numero} ")

"""2- Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 11 produzam resto igual a 2"""

for numero in range(1000,2001):
 if numero % 11 == 2:
  print(numero)

"""3- Faça um programa que leia 5 números e informe a soma e a média dos números."""

soma = 0

for programa in range(1,6):
  numero = float(input(f"Digite um numero: "))
  soma += numero
  print(f"soma = {soma} ")

media = soma/5
print(f"media = {media} ")

"""4- Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número."""

for tabuada in range(1,11):
  for tabuada1 in range(1,11):
    print(f"{tabuada} * {tabuada1} = {tabuada * tabuada1} ")

"""5- Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição.

"""

for tabuada in range(1,11):
  for tabuada1 in range(1,11):
    print(f"{tabuada} * {tabuada1} = {tabuada * tabuada1} ")

"""6- Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro."""

for numero in range(1,21):
  print(numero)
print(list(range(1,21)))

"""7- Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50."""

for numero in range(1,50):
  if numero % 2 != 0:
    print(numero)

"""8- Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles."""

numero = int(input("Digite o primeiro numero "))
numero1 = int(input("Digite o segundo numero "))


for programa in range(numero,  numero1 +1):
  print(programa)

for programa in range(numero1 + 1 ,numero):
  print(programa)

"""9- Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja A foi superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor mostre na tela uma mensagem contendo em quanto foi superado o faturamento."""

lojaA = 0
lojaB = 5400

for cliente in range(5):
  gasto = float(input(f"Digite o gasto do cliente {cliente + 1} "))
  lojaA += gasto
  if lojaA > lojaB:
    print(f"A loja A superou a loja B com um valor arrecadado de R$ {lojaA - lojaB} ")

  elif lojaB > lojaA:
    print(f"A loja B superou a loja A com um valor maior de R$ {lojaB - lojaA} ")

  else:
    print(f"As duas lojas arrecadaram o mesmo valor ")

"""10- Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

numerospares = 0
numerosimpares = 0

for programa in range(10):
  numero = int(input(f"Digite o {programa + 1}, numero inteiro "))
  if numero % 2 == 0:
    numerospares += 1

  else:
    numerosimpares += 1
print(f"A quantidade de numeros pares e {numerospares} e a quantidade de numeros impares e {numerosimpares} ")

"""11- Um funcionário de uma empresa recebe aumento salarial anualmente: Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário."""

# contratado 1995
# salario inicial = 1000
# Em 1996 teve aumento salario de 1,5%
# Em 1997 o salario aumentou o dobro do prc anterior
# Salario atual ?

salario = 1000

salario = float(input(f"Digite o salario inicial do funcionario: "))
# Solicita ao usuário que insira o salário inicial do funcionário e
# converte para float

prc = 0.015 #  Define o percentual de aumento inicial como 1,5%
prc = 2

for i in range(1996,2025): # Loop que itera de 1996 a 2024 (inclusive)

  aumento = salario * prc
 #Calcula o aumento salarial multiplicando o salário pelo percentual de aumento
  salario += aumento #  Adiciona o aumento ao salário
  prc *= 2 #  Dobra o percentual de aumento para o próximo ano

  print(f"salario {i} = salario:.2f")
  #  Imprime o salário para o ano atual com duas casas decimais

"""12-  Faça um programa que peça uma nota, entre zero e dez. Mostre uma
mensagem caso o valor seja inválido e continue pedindo até que o usuário
informe um valor válido.
"""

for programa in range(1,11):
  nota = float(input(f"Digite uma nota: "))
  if nota > 0 and nota <= 10:
    break # Se a nota for valida sai do loop

  else:
    print("\nValor é invalido ")

"""13-  Uma loja tem uma política de descontos de acordo com o valor da
compra do cliente. Os descontos começam acima dos R$500. A cada 100
reais acima dos R$500,00 o cliente ganha 1% de desconto cumulativo até
25%. Por exemplo: R$500 = 1% || R$600,00 = 2% … etc…
Faça um programa que exiba essa tabela de descontos no seguinte formato:
Valordacompra – porcentagem de desconto – valor final
"""

valor = float(input('Digite o valor da compra: R$ '))
contagem = 1
if valor >= 600 and contagem != 0:
  reduzido = valor - 500
  if reduzido >= 100 or contagem <= 24:
    for x in range(999):
      contagem += 1
      reduzido -= 100
      if reduzido < 100 or contagem == 24:
        break

porcentagem = contagem / 100
desconto = valor * porcentagem
final = valor - desconto
print(f'O produto de R${valor:.2f} ficará a partir de R${final:.2f} com {contagem:.0f}% de desconto.')

"""14- Faça um programa que receba a idade de 15 pessoas e que calcule e mostre: a) A quantidade de pessoas em cada faixa etária; b) A percentagem de pessoas na primeira e na última faixa etária, com relação ao total de pessoas:  Até 15 anos  De 16 a 30 anos  De 31 a 45 anos  De 46 a 60 anos  Acima de 61 anos"""

ate15 = 0
de16a30 = 0
de31a45 = 0
de46a60 = 0
mais60 = 0

for pessoas in range(15):
  idade = int(input("Digite a idade da pessoa {pessoa + 1}: ")) # Solicita ao usuário que insira a idade da pessoa e a converte para inteiro

  if idade <= 15:
    ate15 += 1 # incrementa a contagem de pessoas

  elif 16 <= idade >= 30:
    de16a30 += 1

  elif 31 <= idade >= 45:
    de31a45 += 1

  elif 46 <= idade >= 60:
    de46a60 += 1

  else:
    mais60 += 1
    print(f"Quantidade de pessoas por faixa etaria\n \te 15 anos: {ate15} pessoa\n de16 a 30 anos: {de16a30} pessoa\n de31 a 45 anos: {de31a45} pessoas\n de46 a 60: {de46a60} pessoa\n {((100 * ate15)/15):.2f}% das pessoas têm até 15 a nos\n{((100 * mais60) / 15):.2f}% das pessoas têm mais de 6 0 anos")

"""15- Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

base = int(input("Digite o valor da base: "))
expoente = int(input("Digite o valor do expoente: "))
r = expoente * base

for i in range(expoente):
  if base == 1: # Verifica se a base é igual a 1
    r = base # Se sim, o resultado recebe o valor da base

  else:
    r *= base # Se não, multiplica o resultado pela base (eleva a base ao expoente)
    print(f"Resultado {r} ") # Imprime o resultado da operação de exponenciação

"""16- Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário. O programa deverá mostrar também o número de divisões que ele executou para encontrar os números primos. Serão avaliados o funcionamento, o estilo e o número de testes (divisões) executados."""

n = int(input("Digite um numero: "))

for numeroTestado in range(1, n+1): #  Loop que itera de 1 até o número inserido pelo usuário (inclusive)
  for numeroDivisor in range(numeroTestado): #  Loop que itera de 0 até o número testado (exclusive)

   print(f"{numeroTestado} / {numeroDivisor+1} = {numeroTestado /(numeroDivisor+1)} com o resto {numeroTestado%(numeroDivisor+1)}")
#  Imprime a divisão e o resto da divisão entre o número testado e o número divisor + 1

if numeroTestado % (numeroDivisor+1) == 0:
  # Verifica se o número testado é divisível pelo número divisor + 1

  if 1 != numeroDivisor+1 != numeroTestado: # Verifica se o número divisor + 1 é diferente de 1 e do número testado
    print("não é primo\n") # Se sim, imprime que o número não é primo e quebra o loop interno

elif numeroDivisor+1 == numeroTestado: #  Se o número divisor + 1 for igual ao número testado
  print("número é primo\n") # Imprime que o número é primo